version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: eladshoham/flask-openai-qa:1.0.0
    build: .
    ports:
      - "5000:5000"
    env_file:
      - variables.env
    depends_on:
      - flask_db

  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
